---
services:
  arma-reforger:
    build: .
    platform: linux/amd64
    container_name: arma-reforger
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "19999:19999/udp"  # RCON
    volumes:
      - ./docker_default.json:/reforger/Configs/server.json:ro
      - steamcmd:/steamcmd
      - reforger:/reforger
      - ./reforger/configs:/reforger/Configs
      - ./reforger/profile:/home/profile
      - ./reforger/workshop:/reforger/workshop
    environment:
      - ARMA_CONFIG=server.json

volumes:
  steamcmd:
  reforger:

